also save errors on setup script checks

diff --git a/.github/workflows/check_scripts.yml b/.github/workflows/check_scripts.yml
--- a/.github/workflows/check_scripts.yml
+++ b/.github/workflows/check_scripts.yml
@@ -67,6 +67,32 @@ jobs:
 
           ./run.sh -rc rugby_ball
 
+      # ---------------------------------------------------------------------- #
+      # Report errors if any step fails
+      # ---------------------------------------------------------------------- #
+      - name: Report errors
+        if: failure()
+        run: |
+          echo "Errors encountered during script execution. Please check the logs for details."
+          logs=($(find logs/ -name "error.log"))
+
+          for file in ${logs[@]}; do
+            if [[ -s $file ]]; then
+              printf "\nContents of $file:\n" >&2
+              cat $file >&2
+            elif [ -f $file ]; then
+              rm -fr $(dirname $file)
+            fi
+          done
+
+      - name: Save logs as artifact
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: setup-script-logs
+          path: logs/**/*.log
+          overwrite: true
+
   setup-action:
     name: Check setup action
     runs-on: ubuntu-latest
@@ -132,7 +158,7 @@ jobs:
 
           for file in ${logs[@]}; do
             if [[ -s $file ]]; then
-              echo "Contents of $file:" >&2
+              printf "\nContents of $file:\n" >&2
               cat $file >&2
             elif [ -f $file ]; then
               rm -fr $(dirname $file)
@@ -143,6 +169,6 @@ jobs:
         if: failure()
         uses: actions/upload-artifact@v4
         with:
-          name: script-logs
+          name: setup-action-logs
           path: logs/**/*.log
           overwrite: true
