Refactor CI system and add checks (#226)
Introduce a workflow that checks pull requests on the develop branch for
linting, formatting, and compilation, ensuring code quality before
merging.

Add a number of updates to our entire CI system.

diff --git a/.github/workflows/check_compile.yml b/.github/workflows/check_compile.yml
--- a/.github/workflows/check_compile.yml
+++ b/.github/workflows/check_compile.yml
@@ -1,5 +1,6 @@
-# This check is used to ensure documentation can be built from the main branch.
-name: Check Neko-TOP compilation and tests
+# This workflow checks the compilation of the Neko-TOP library.
+
+name: Check Neko-TOP compilation
 
 # This workflow is only defined here. It is triggered from other workflows.
 on:
@@ -7,10 +8,6 @@ on:
     inputs:
       neko-version:
         description: "The version of Neko to use."
-        required: true
-        type: string
-      pfunit-version:
-        description: "The version of pFUnit to use."
         required: true
         type: string
       json-fortran-version:
@@ -24,86 +21,12 @@ on:
 jobs:
 
   # -------------------------------------------------------------------------- #
-  # Define the dependency cache jobs that will be run in this workflow. Each of
-  # these jobs will cache the dependencies for a specific library.
-
-  cache-json-fortran:
-    name: Cache JSON-Fortran
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup json-fortran
-        id: setup-json-fortran
-        uses: ./.github/actions/setup_json-fortran
-        with:
-          version: ${{ inputs.json-fortran-version }}
-
-  cache-pfunit:
-    name: Cache pFUnit
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup pFUnit
-        id: setup-pfunit
-        uses: ./.github/actions/setup_pfunit
-        with:
-          version: ${{ inputs.pfunit-version }}
-
-  cache-gslib:
-    name: Cache GSLib
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup GSLib
-        id: setup-gslib
-        uses: ./.github/actions/setup_gslib
-
-  cache-neko:
-    name: Cache Neko
-    runs-on: ubuntu-latest
-    needs:
-      - cache-json-fortran
-      - cache-pfunit
-      - cache-gslib
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Get json-fortran
-        id: get-json-fortran
-        uses: ./.github/actions/setup_json-fortran
-        with:
-          version: ${{ inputs.json-fortran-version }}
-
-      - name: Setup neko
-        id: setup-neko
-        uses: ./.github/actions/setup_neko
-        with:
-          json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}
-          version: ${{ inputs.neko-version }}
-
-  # -------------------------------------------------------------------------- #
   # Define the compilation and testing job that will be run in this workflow.
   # This job will build the Neko-TOP code in debug mode and run the unit tests.
 
   neko-top-debug:
-    name: Test Neko-TOP
+    name: Compile Neko-TOP
     runs-on: ubuntu-latest
-    needs:
-      - cache-json-fortran
-      - cache-neko
-      - cache-pfunit
-      - cache-gslib
 
     steps:
       # ---------------------------------------------------------------------- #
@@ -141,16 +64,6 @@ jobs:
           json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}
           version: ${{ inputs.neko-version }}
 
-      - name: Get pFUnit
-        id: get-pfunit
-        uses: ./.github/actions/setup_pfunit
-        with:
-          version: ${{ inputs.pfunit-version }}
-
-      - name: Get GSLib
-        id: get-gslib
-        uses: ./.github/actions/setup_gslib
-
       # ---------------------------------------------------------------------- #
       # Build and test the code
       # ---------------------------------------------------------------------- #
@@ -159,24 +72,62 @@ jobs:
         env:
           JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
           NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
-          PFUNIT_DIR: ${{ steps.get-pfunit.outputs.install-dir }}
-          GSLIB_DIR: ${{ steps.get-gslib.outputs.install-dir }}
         run: |
           cmake -B build -S . -G Ninja --fresh \
             -DCMAKE_BUILD_TYPE=Debug \
+            -DBUILD_TESTING=ON \
             -DJSON_FORTRAN_DIR=$JSON_FORTRAN_DIR \
-            -DNEKO_DIR=$NEKO_DIR -DPFUNIT_DIR=$PFUNIT_DIR \
-            -DBUILD_DOCS=OFF -DBUILD_TESTING=ON -DDEVICE_TYPE=OFF
+            -DNEKO_DIR=$NEKO_DIR
 
       - name: Building Library
         run: |
           cmake --build build --parallel
 
+      - name: Running Tests
+        run: |
+          ctest --test-dir build --output-on-failure --parallel
+
+      # ---------------------------------------------------------------------- #
+      # Run a rugby ball example to ensure everything works as expected
+      # ---------------------------------------------------------------------- #
+
       - name: Building Examples
         run: |
           cmake --build build --target Examples --parallel
 
-      - name: Unit tests
+      - name: Run Rugby Ball
+        env:
+          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
+          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
         run: |
-          ctest --test-dir build --output-on-failure --stop-on-failure
+          # Adjust the end time and max iterations for the rugby ball case
+          sed -i -r 's/"end_time":.*/"end_time": 1e-3,/g' examples/rugby_ball/rugby_ball.case
+          sed -i -r 's/"max_iterations":.*/"max_iterations": 2,/g' examples/rugby_ball/rugby_ball.case
 
+          ./run.sh -rc rugby_ball
+
+      # ---------------------------------------------------------------------- #
+      # Report errors if any step fails
+      # ---------------------------------------------------------------------- #
+      - name: Report errors
+        if: failure()
+        run: |
+          echo "Errors encountered during script execution. Please check the logs for details."
+          logs=($(find logs/ -name "error.log"))
+
+          for file in ${logs[@]}; do
+            if [[ -s $file ]]; then
+              printf "\nContents of $file:\n" >&2
+              cat $file >&2
+            elif [ -f $file ]; then
+              rm -fr $(dirname $file)
+            fi
+          done
+
+      - name: Save logs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: check-compile-logs
+          path: logs/**/*.log
+          overwrite: true
