Fix/cicd (#21)

diff --git a/.github/workflows/pr_main.yml b/.github/workflows/pr_main.yml
--- a/.github/workflows/pr_main.yml
+++ b/.github/workflows/pr_main.yml
@@ -25,7 +25,21 @@ jobs:
       - check_formatting
       - check_documentation
       - check_compilation
+
     runs-on: ubuntu-latest
+    env:
+      check_formatting: ${{ needs.check_formatting.result }}
+      check_documentation: ${{ needs.check_documentation.result }}
+      check_compilation: ${{ needs.check_compilation.result }}
+
     steps:
       - name: All checks passed
-        run: echo "All checks passed"
+        run: |
+          if [ "$check_formatting" != "success" ]; then
+            echo "Formatting check failed"
+            exit 1
+          elif [ "$check_compilation" != "success" ]; then
+            echo "Compilation check failed"
+            exit 1
+          fi
+          echo "All checks passed"
